[tool.poetry]
name = "mysite"
version = "0.1.0"
description = "Yardgrowers application"
authors = ["Lauri Suuster"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
