# Generated by Django 4.2.7 on 2023-12-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product_images/thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product_images"
            ),
        ),
    ]
