# Generated by Django 4.2.7 on 2024-01-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_intent',
            new_name='merchant_id',
        ),
    ]
