# Generated by Django 4.2.7 on 2024-01-02 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_rename_payment_intent_order_merchant_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
