# Generated by Django 4.2.7 on 2024-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_rename_merchant_id_order_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
