# Generated by Django 4.2.7 on 2024-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.CharField(choices=[('postage', 'Postage'), ('home_delivery', 'Home Delivery'), ('self_pickup', 'Self Pickup')], default='postage', max_length=20),
        ),
    ]
