# Generated by Django 4.2.7 on 2024-01-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_orderitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Product is in the draft stage and not yet ready for publishing.'), ('waitingapproval', 'Waiting Approval - Product is submitted and waiting for approval.'), ('active', 'Active - Product is live and available for purchase.'), ('inactive', 'Inactive - Product is not currently available for purchase.'), ('outofstock', 'Out of Stock - Product is temporarily unavailable but will be restocked.'), ('soldout', 'Sold Out - Product is completely sold out and not available for purchase.')], default='active', max_length=50),
        ),
    ]
