# Generated by Django 4.2.7 on 2024-01-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
