# Generated by Django 4.2.7 on 2024-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('declined', 'Declined')], default='received', max_length=20),
        ),
    ]
