"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5w61gr4h8wjkkb#sjx)o-)w==4o#5d#+bk7fgc8+w#tzq+@uru'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['yardgrowers.com', 'yardgrowers.co.nz' ]

# Session key 
CART_SESSION_ID = 'cart'
# How many seconds the session is going to be live: Go above 1 day and cart will be emptied 
SESSION_COOKIE_AGE = 86400

LOGIN_URL = 'login'

# After logging in redirect user to myaccount page.

LOGIN_REDIRECT_URL = 'myaccount'

# After logging out redirect user to index page.

LOGOUT_REDIRECT_URL = 'index'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add my apps
    'core',
    'product',
    'userprofile',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'mysite.urls'

# Public API key from stripe

STRIPE_PUB_KEY= 'pk_test_51OTA1bFBUhSdzIr5KNfEBPhu2I0kp4oXVv6BiYOBXCCI6rGBATnF5Mc8u2WvwGKgLj9pntCAwWQNfqjHtvBrbcWS00TWPB6z9q'

# Secret key from stripe

STRIPE_SECRET_KEY = 'sk_test_51OTA1bFBUhSdzIr5Dgk2e2NdRVkSMuP08hGBilxEdcwhi6zGS1tOEkL80QYBDxMyBuyfMqpDFfLwUcbMABlfPS6f00f4LUfPij'

WEBSITE_URL = 'yardgrowers.com'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Media URL for images 
MEDIA_URL =  'media/'
#Specify route for the files in the server (check line 15)
MEDIA_ROOT = BASE_DIR / 'media' 

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# mailtrap for contact form 

# Tells django wich email sending method to use
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '16fd4211307d72'
EMAIL_HOST_PASSWORD = '5e3f8e3d68610b'
# Change ports if connection is blocked by firewall
EMAIL_PORT = '2525'
EMAIL_USE_TLS = True
# Must be false otherwise SMTPServerDisconnected at /contac
EMAIL_USE_SSL = False